### PR TITLE
Feature/nova rate limits better filtering

### PR DESCRIPTION
**Pull request by rafaduran**
I've done some changes that I think improve how `nova rate-limits` command show limits, so sending them back. I've also added some tools from Nova in order to build a virtualenv.

### CODE REVIEW

**Comment by klmitch** [comment]
I am not happy with having the nova virtualenv tools pulled in.  My major objection is the incorrect *-requires files, but overall, I feel like this is far too heavy handed.  I'm willing to consider a tox setup, for both nova_limits and turnstile, but it has to be in a separate patch.

The other changes look OK to me…

**Comment by rafaduran** [comment]
@klmitch  I've rebased, removing the virtualenv stuff, so I think it now looks better. About a tox setup, I'm not really sure how to do that (I never work with tox before), but I will check it, thought I might need some help.

**Comment by klmitch** [comment]
OK, I've thought about your change some more.  The change to filter out other tenants makes perfect sense; I consider that a bug fix.  However, the "not showing limits twice" is changing intentional behavior: I wanted rate-limited users to see both the raw rule and the specific bucket that was affecting them.

**Comment by rafaduran** [comment]
@klmitch the "not showing limits twice" change is not about a personal preference but how works Nova default rate limit middleware and I would like nova_limits behaviour to be as close as the default one; thought I also think from the point of view of users is clearer. In worst case, I think we can add a flag so we support both cases, what do you think?

**Comment by klmitch** [comment]
Sorry I let this drop on the floor; got busy with other things and totally forgot about it…

The difference with the Nova default rate limiting is that the Nova rate limiting has a single bucket; it does not differentiate between users at all, thus it can't really set a precedent for this specific case.

I will accept a flag to support both cases; my preference is that it default to the existing behavior, however.

**Pull request closed without merging**
